[sources]
lmp_index = "http://mis.ercot.com/misapp/GetReports.do?reportTypeId=12300&reportTitle=LMPs%20by%20Resource%20Nodes,%20Load%20Zones%20and%20Trading%20Hubs&showHTMLView=&mimicKey"
adders_index = "http://mis.ercot.com/misapp/GetReports.do?reportTypeId=13221&reportTitle=Real-Time%20ORDC%20and%20Reliability%20Deployment%20Price%20Adders%20and%20Reserves%20by%20SCED%20Interval&showHTMLView=&mimicKeys"

[download]
dl_root = "http://mis.ercot.com"